Deploiement

diff --git a/.github/workflows/main_pipeline.yml b/.github/workflows/main_pipeline.yml
--- a/.github/workflows/main_pipeline.yml
+++ b/.github/workflows/main_pipeline.yml
@@ -15,7 +15,6 @@ env:
 
 jobs:
   # --- JOB 1 : INSTALLATION ET VALIDATION ---
-  # Vérifie la syntaxe et le style du code Terraform
   installation_et_validation:
     name: Installation & Validation
     runs-on: ubuntu-latest
@@ -42,7 +41,6 @@ jobs:
         working-directory: ${{ env.WORKING_DIR }}
 
   # --- JOB 2 : SCAN DE SÉCURITÉ ---
-  # Analyse les vulnérabilités et le respect des bonnes pratiques
   securite_et_lint:
     name: Scan Sécurité (Checkov & TFLint)
     runs-on: ubuntu-latest
@@ -56,7 +54,7 @@ jobs:
         with:
           directory: .
           framework: terraform
-          soft_fail: false # Bloque si une erreur de sécurité non-ignorée est trouvée
+          soft_fail: false 
 
       - name: Installation TFLint
         uses: terraform-linters/setup-tflint@v4
@@ -68,7 +66,6 @@ jobs:
         working-directory: ${{ env.WORKING_DIR }}
 
   # --- JOB 3 : PLANIFICATION (CONFIGURATION) ---
-  # Prépare les changements sans les appliquer
   configuration_plan:
     name: Planification
     runs-on: ubuntu-latest
@@ -100,12 +97,15 @@ jobs:
       - name: Génération du Plan
         id: plan
         run: |
+          set +e
           terraform plan \
             -var="db_password=${{ secrets.TF_VAR_DB_PASSWORD }}" \
             -out=tfplan \
             -detailed-exitcode
+          
+          # Capture de l'exit code (0=pas de changement, 1=erreur, 2=changements détectés)
+          echo "exitcode=$?" >> $GITHUB_OUTPUT
         working-directory: ${{ env.WORKING_DIR }}
-        continue-on-error: true
 
       - name: Sauvegarde du Plan (Artefact)
         uses: actions/upload-artifact@v4
@@ -115,13 +115,12 @@ jobs:
           retention-days: 1
 
   # --- JOB 4 : DÉPLOIEMENT ---
-  # Applique les changements sur l'infrastructure réelle
   deploiement:
     name: Déploiement Production
     runs-on: ubuntu-latest
     needs: configuration_plan
-    # Se lance uniquement sur 'main' si des changements ont été détectés (Exit Code 2)
-    if: github.ref == 'refs/heads/main' && needs.configuration_plan.outputs.plan_exit_code == '2'
+    # Correction de la condition : On accepte develop pour tes tests de visualisation
+    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') && needs.configuration_plan.outputs.plan_exit_code == '2'
     environment: production
     steps:
       - name: Checkout du code
